version: '3'
services:
  nginx:
    build:
      context: ./services/nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - web
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
  web:
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@postgres:5432/app_production
      RAILS_SERVE_STATIC_FILES: "true"
    build:
      context: ./services/web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./services/web/app:/app
    expose:
      - "3000"
    depends_on:
      - postgres
